version: '3'

services:
  backend:
    container_name: backend_container
    build:
      context: ./backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "3000:3000"

  frontend:
    container_name: frontend_container
    depends_on:
      - backend
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
